### ISSUE TITLE
Submission Review

### ISSUE THREAD

**Issue by ivan-adakerja** [mriskyn/fb-messenger-bot#1]
Hi @mriskyn ! I am Ivan 👋 😄 from AdaKerja
Thanks for the submission, here I have my review result for you.

- [-] no test. better try to add test for main flow
- [+] documentation looks good
- [+] code style looks neat and folder structure clear
- [+] use db - postgre. have each models, user & messages
- [-] state is bad, is based on user message. we as the owner can't control the flow (name -> birthday -> calculate / bye)
  - if user say 'hi' all times bot can't continue
  - thankyou and goodbye will be save as name 
  - save in localstorage, could cause race condition when 2 concurrent user chatting at same time
- [-] [birthday not fully correct](https://user-images.githubusercontent.com/70680973/151696950-45ffce24-733a-4ff4-bf6d-9adec01bdeeb.png)

**Comment by darczodiac** [comment]
Hi @ivan-adakerja 
Thanks for reviewing my submission. I learn a lot from that.

I already fix the minus point from your review, except for the testing.

I think it should be using E2E testing and i tried using [Cypress](https://docs.cypress.io/). And my problem is i can't find the document selector for messenger button because it is in iframe contentDocument.

**Comment by ivan-adakerja** [comment]
Ello @mriskyn, sorry for late response.

Actually no need E2E, start small and simple with unit test, maybe mocha / jest for example. 
You could then test birthday calculation / api response / state flow / etc.
Understanding mock / stub also great to start.

Anyway, saw your improvement there 👍 

- birthday is fixed
- introduced mongo to fix the state flow issue

But I have to ask, **why introduce mongo? why not extend and use current sequalize?**

**Comment by darczodiac** [comment]
I was thinking i'll use mocha / jest to test the API. But when i read the requirement should test the flow, that's where i think i should test with E2E.

I was reading some articles out there, instead using in memory storage like redis, try to use mongo. I also think use of mongo is unstructurized schema.

**Comment by ivan-adakerja** [comment]
@mriskyn 

Ahh okay, it's not really meant for the integration test. So you able to create unit test?

But on postgre or any sql database you could have null value to right? Do you understand the risk introducing 2 database there?

**Comment by darczodiac** [comment]
yes, i can make the test.

I think soo. and i dont know the risk using 2 databases, or should i migrate to postgre?

**Comment by ivan-adakerja** [comment]
@mriskyn one of simple risk having 2 database is we will questioning the source of truth, which one is the true "users" if there is 2 database exists with "users" on it. 
at the same time its okay too to have 2 database if it serves different services, so it could form microservices.
